### Listar transações
GET http://localhost:5000/api/transactions

### Criar transação 1
POST http://localhost:5000/api/transactions
Content-Type: application/json

{
    "description": "Salário",
    "value": 8000,
    "type": "Income",
    "category": "Receita"
}

### Criar transação 2
POST http://localhost:5000/api/transactions
Content-Type: application/json

{
    "description": "Aluguel",
    "value": 1500,
    "type": "Outcome",
    "category": "Moradia"
}

### Listar uma transação
GET http://localhost:5000/api/transactions/1

### Deletar uma transação
DELETE http://localhost:5000/api/transactions/2

### Atualizar transação inteira
PUT http://localhost:5000/api/transactions/3
Content-Type: application/json

{
    "description": "Teste",
    "value": 123.45,
    "category": "teste",
    "type": "outcome"
}

### Atualizar transação por propriedade
PATCH http://localhost:5000/api/transactions/2
Content-Type: application/json

{
    "category": "casa"
}

### Verificar saldo
GET http://localhost:5000/api/summary

### Verificar entradas
GET http://localhost:5000/api/summary/incomes

### Verificar saídas
GET http://localhost:5000/api/summary/outcomes

### Verificar categoria
GET http://localhost:5000/api/summary/receita