### Register user 1
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "FullName": "John Doe",
    "Email": "johndoe@email.com",
    "Password": "JohnPassword"
}

### Login user 1
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "Email": "johndoe@email.com",
    "Password": "JohnPassword"
}

### Create Post 1 with Logged User
POST http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImVhMTg0OWViLWYwNmUtNGU1Yi05YTQwLTVmMDE4NWQ5ZTk0NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG5kb2VAZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzgzNjY3ODYzLCJpc3MiOiJCbG9nQXBpIiwiYXVkIjoiQmxvZ0FwaSJ9.tsIIvlQV7wKtoNdyIXWipaqGCl1Cgb1fd6mkfL8i1xw
Content-Type: application/json

{
    "Title": "Blog ASP.NET Core",
    "Content": "Esse blog está sendo construído utilizando asp.net core, entity framework, identity framework e JWT."
}

### Create Post 2 with Logged User
POST http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImVhMTg0OWViLWYwNmUtNGU1Yi05YTQwLTVmMDE4NWQ5ZTk0NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG5kb2VAZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzgzNjY3ODYzLCJpc3MiOiJCbG9nQXBpIiwiYXVkIjoiQmxvZ0FwaSJ9.tsIIvlQV7wKtoNdyIXWipaqGCl1Cgb1fd6mkfL8i1xw
Content-Type: application/json

{
    "Title": "Meu Segundo Post",
    "Content": "Esse aqui é o conteúdo!"
}

### List all posts of all users
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImVhMTg0OWViLWYwNmUtNGU1Yi05YTQwLTVmMDE4NWQ5ZTk0NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG5kb2VAZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzgzNjY3ODYzLCJpc3MiOiJCbG9nQXBpIiwiYXVkIjoiQmxvZ0FwaSJ9.tsIIvlQV7wKtoNdyIXWipaqGCl1Cgb1fd6mkfL8i1xw

### List one post by id
GET http://localhost:5000/api/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImVhMTg0OWViLWYwNmUtNGU1Yi05YTQwLTVmMDE4NWQ5ZTk0NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG5kb2VAZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzgzNjY3ODYzLCJpc3MiOiJCbG9nQXBpIiwiYXVkIjoiQmxvZ0FwaSJ9.tsIIvlQV7wKtoNdyIXWipaqGCl1Cgb1fd6mkfL8i1xw
